# Generated by Django 6.0.4 on 2026-04-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Languages'), ('frameworks', 'Frameworks'), ('frontend', 'Frontend'), ('databases', 'Databases'), ('tools', 'Tools & Platforms'), ('concepts', 'Core Concepts')], default='languages', max_length=20),
        ),
    ]
